// Twelve "ideal" minimalistic image prompts supplied by the team. They are the
// gold-standard reference for the minimalistic presentation style: cinematic,
// editorial, restrained — one idea per slide, near-monochrome palettes, large
// condensed/stencil typography with a stat-plus-consequence subtext, heavy film
// grain and deep vignette, and verbatim on-image text. Claude learns the style
// from these few-shot exemplars rather than from a written rule block.
//
// Each example has its trailing "Aspect ratio 16:9." sentence removed — aspect
// ratio is set separately as an API parameter and must never appear in output.
// For the three prompts that shipped as a short concept plus an expanded
// "Image Prompt:" version (7, 8, 9), the expanded version is used here.

export const MINIMALISTIC_EXAMPLE_PROMPTS = [
  `Hyper-dramatic 3D product visualization render, Octane Render quality, studio-perfect lighting with cinematic theatrical flair. An enormous chess board fills the frame — each square rendered in polished black and deep charcoal marble, edges beveled, surface reflecting everything above it. Occupying the center squares: a single large, meticulously detailed Unilever-branded delivery truck rendered in 3D — pristine white paint, chrome bumper, clean logo on the panel, headlights on, engine visibly running (heat shimmer above the hood). Surrounding this center truck from three sides, closing in with visible tactical intent: multiple smaller competitor delivery trucks — rendered in cold grey and black, aggressive angular styling, no branding visible, uniformly threatening. Several competitor trucks have already moved into squares that are now turning grey-charcoal beneath them, "captured" squares. Two gold squares directly ahead of the Unilever truck glow warmly — still available, still open. Dominating the background of the scene: a monumental crystal hourglass, easily three times the height of the trucks, backlit by an intensely saturated red-orange gradient — sand visibly almost fully drained to the bottom chamber, only a thin trickle remaining at the neck. The hourglass casts dramatic long red shadows across the chessboard. Floating in the upper portion of the image in massive red condensed typography: "EVERY MONTH OF DELAY IS A MONTH THEY EMBED." Fine subtext beneath: "First-mover distribution advantage. Real. Durable. Nearly impossible to reverse." Dramatic rim lighting on all elements. Deep shadow vignette on frame edges.`,

  `Ultra-realistic editorial infographic render, stark white background with a faint cool grey paper texture — like a premium financial publication spread. The dominant element is a thick black horizontal timeline bar running the full width of the slide at the vertical center, with precise year markers notched below it: 2010, 2012, 2014, 2016, 2018, 2020, 2022, 2024, 2025. Above the timeline, at each conquered year, sits a meticulously rendered miniature tombstone — dark grey granite, beveled edges, slightly weathered — each with a clean serif RIP engraving and a category label beneath it in small tight caps: "EMAIL — RIP 2016 / Killed by: GPT Mail", "DOCUMENTS — RIP 2018 / Killed by: Notion AI", "SPREADSHEETS — RIP 2020 / Killed by: Excel Copilot", "CODE — RIP 2022 / Killed by: GitHub Copilot", "SCHEDULING — RIP 2023 / Killed by: Reclaim AI", "CRM — RIP 2024 / Killed by: Salesforce Einstein." Each tombstone casts a precise short shadow downward. The tombstones increase slightly in size left to right, building visual momentum. At the far right end of the timeline — 2025 — the tombstone is missing. In its place: a single blinking red cursor, hovering above the timeline on a clean white pedestal block. Beside the cursor, a category label in bold red type: "PRESENTATIONS." No RIP. No date. Just the cursor, blinking. Below the timeline, a thin dark rule separator, then in small precise sans-serif across the full width: "Five categories disrupted. One remains. The cursor is blinking." At the top of the slide in massive bold dark condensed typography: "EVERY CATEGORY HAS FALLEN. ONE HASN'T." Subtext in smaller grey italic beneath: "AI didn't forget presentations. It just hasn't arrived yet." Print-precise linework. Zero decorative noise. McKinsey-cold editorial finish.`,

  `Hyper-realistic product UI showcase render, deep matte charcoal background — almost black, with an ultra-subtle dark navy gradient bleeding in from the top edge. The entire frame is anchored by a single large, dramatically lit UI screenshot of the HyperBeing application — rendered as if floating at a very slight 4-degree tilt on a dark glass surface that reflects it back dimly below. The interface itself is meticulously detailed: dark-mode canvas, left panel showing an AI prompt input bar with a half-typed instruction — "Create a Series A investor pitch for a B2B SaaS with $3M ask—" — the cursor blinking mid-sentence. The center canvas shows a partially generated slide deck — five slide thumbnails in the left rail, the active slide rendered in crisp full detail: clean headline typography, a sharp data visualization auto-populated, smart layout perfectly balanced. The right panel shows an AI suggestions column — three content recommendations visible, each with a small glowing blue "Apply" button. Every UI element is pixel-sharp, font sizes readable, hover states visible, the whole interface radiating quiet intelligence and precision. Above the interface, in large matte white condensed typography with zero glow or effect: "YOU DESCRIBE THE DECK. IT BUILDS THE ARGUMENT." Directly below the UI in clean small sans-serif, three feature callouts arranged horizontally like a spec strip — each separated by a thin vertical rule: "Prompt-to-Deck in 60 seconds" | "AI Layout + Copy Engine" | "Credit-based. No subscriptions." No shields. No metaphors. No floating geometry. Just the product, brutally clear, doing its job. Dramatic single-source spotlight from top-left casting a razor-thin highlight along the top edge of the UI frame. Everything else: deep shadow.`,

  `Stark, deeply moody cinematic interior, shot on Leica SL2 with 35mm lens, available light only. A sprawling open-plan office at late night — most lights off, only cold blue monitor glow illuminating the space. Rows of empty desks, but at one isolated workstation sits a single figure — collared shirt, sleeves rolled up, hunched forward — surrounded by the wreckage of a presentation gone wrong: a laptop screen showing a bloated, ugly 47-slide PowerPoint deck, scattered printed slide printouts across the desk, a coffee mug tipped sideways, sticky notes covering every surface. On the monitor in the background, a clock UI reads 2:47 AM. A second monitor shows a blank slide with only a cursor blinking. The posture of the figure radiates exhaustion and quiet frustration. On the far wall behind him, in large white stencil block letters, partially lit by a single cold fluorescent tube: "THE AVERAGE PROFESSIONAL SPENDS 4 HOURS BUILDING ONE DECK." Beneath it in smaller stencil: "Most of it is guesswork. None of it is strategy." Cinematic color grade: crushed blacks, cold blue-white ambient, single desaturated amber glow from the monitor. Heavy film grain. Deep shadow vignette on all four edges.`,

  `Stark moody cinematic close-up, shot on Sony A7 IV, 85mm f/1.4, available light. A Pakistani university student, male, 21, sitting cross-legged on grass — LUMS lawn, palm trees soft-focus in background, golden afternoon light. He's wearing a faded vintage oversized tee, wireless earbuds in. His phone screen dominates the left third of the frame — held up at a natural angle, screen fully visible and hyper-realistic: Netflix app open, playing a Korean drama, Korean subtitles visible, progress bar at 47 minutes. On the right side of his lap: an open takeout container with Korean ramen, chopsticks resting on the edge. His expression is completely absorbed — not performing for anyone, just living it. He doesn't own a passport. He's never left Pakistan. On the dark grassy ground below him, in bold white stencil type casting a faint shadow: "HE'S NEVER LEFT PAKISTAN. HE'S ALREADY LIVING GLOBALLY." Fine subtext beneath: "73% of Pakistani Gen Z consume foreign culture daily. Food is next." Cinematic color grade: warm golden-hour tones, slight teal in the shadows. Heavy film grain.`,

  `Hyper-dramatic cinematic photograph render, shot on Leica SL2, 35mm, available light only. Interior of a Pakistan Airlines cabin — warm overhead cabin lighting, real economy seat textures, tray tables down. Tight on a single Pakistani woman, mid-20s, dupatta loosely around her shoulders, AirPods in — she's holding a premium matte black Knorr Global Flavors noodle cup with both hands, steam rising directly into the cabin light above, her eyes closed in genuine involuntary pleasure, head tilted slightly back. The cup's Knorr red branding and "Global Flavors" text are crisp and readable. Through the oval window beside her: clouds at 35,000 feet, golden hour light bleeding in. In the seat behind her, barely in focus: another passenger mid-slurp, phone up filming themselves eating. Floating in the upper left in large white condensed stencil typography against the dark cabin ceiling: "WE DIDN'T WAIT FOR PAKISTAN TO DISCOVER THE WORLD." Fine white subtext beneath: "Phase 1: Knorr Global Flavors. Live. In-flight. First in Pakistan." Cinematic color grade: warm amber-gold on subjects, deep cool blue in the cabin shadows. Heavy film grain. Deep vignette on all four edges.`,

  `Stark deeply moody cinematic top-down photograph render, Leica SL2, 50mm Noctilux f/0.95, single overhead spotlight. A large weathered paper map of Karachi spread flat across a dark aged oak table — street grids, DHA, Gulshan, university locations all legible, slightly yellowed at the edges, one fold crease running diagonally. Three oversized antique brass map pins driven firmly into the map — each carrying a small rectangular white card flag on a thin wire: PIN 1 placed over a university cluster, flag reading "PLACE" in bold dark condensed type, subtext in tiny caps: "Show up where they live." PIN 2 placed over a food street zone, flag reading "PARTICIPATION", subtext: "Make the experience the content." PIN 3 placed over a dense residential area, flag reading "PROOF", subtext: "Real reactions. Real volume." A single red thread connects all three pins, pulled taut in a triangle, casting a thin shadow on the map. Around the map on the table: a Knorr Global Flavors boarding pass card — printed, premium stock, "DESTINATION: SEOUL" visible. A smartphone lying face-up, screen showing Instagram Reels recording interface — red record button active, live view showing a steaming noodle bowl. A single printed sheet — bar chart, impressions line spiking sharply upward, "5M+" annotated at the peak. One overhead industrial pendant lamp casting a perfect circle of warm amber light on the map center, everything beyond the lamp radius falling into near-total darkness. Floating in the dark upper zone of the frame in large white condensed stencil bold: "THREE PINS. ONE CAMPAIGN." Fine white subtext beneath: "Place. Participation. Proof." Cinematic color grade: warm amber on the map, cool dark shadows everywhere else. Heavy film grain. Deep vignette on all edges.`,

  `Hyper-dramatic 3D product visualization render, Octane Render quality, studio-perfect rim lighting. Three identical iPhone 15 Pro Max handsets in black titanium floating at a very slight upward angle above a pure matte obsidian surface that reflects them dimly below — arranged side by side with generous dark space between each. Each phone screen is hyper-realistically rendered, pixel-sharp, fully readable. LEFT PHONE screen: Google Maps app open — map of Karachi visible, a university campus location pinned with a red marker, blue navigation route drawn from a starting point, ETA visible, search bar reading "IBA Karachi." A small floating label card above this phone in clean white sans-serif: "01 — PLACE." CENTER PHONE screen: TikTok recording interface — portrait mode active, red record button glowing, duration counter at 0:31. In the live viewfinder: a Pakistani girl in hijab, black blindfold across her eyes, holding a steaming Knorr noodle bowl, mid-laugh, completely unscripted. Three live comment bubbles floating up the right side of the screen: "which flavor 😭", "she's so done 💀", "KNORR ATE." A floating label card above: "02 — PARTICIPATION." RIGHT PHONE screen: Instagram Professional Dashboard — clean analytics layout, a bold impressions line graph spiking dramatically upward, peak value annotated "5.2M" in large numerals, follower growth bar below it, account name "@knorrpakistan" visible at top. A floating label card above: "03 — PROOF." Below all three phones on the obsidian surface, their reflections glowing softly. Dramatic rim lighting — thin electric white highlight along the left edge of each phone, deep shadow on the right. Floating in the uppermost dark zone of the frame in large white condensed bold: "THREE SCREENS. ONE STRATEGY." Fine subtext: "Place. Participation. Proof." Pure black background. Cinematic studio lighting. Heavy vignette.`,

  `Breathtaking wide cinematic photograph render, shot on Canon R5 with 24mm f/1.8, golden hour light, shallow depth of field pulling focus across the frame left to right. Single continuous scene set on a Pakistani university campus ground — IBA Karachi aesthetic, warm brick architecture soft in the far background, natural lawn, golden afternoon light raking across the whole frame. The image reads left to right in three organic beats with no hard dividers — just natural depth of field transitions. LEFT THIRD — sharp focus: a Pakistani male student, 21, kurta-hoodie, backpack on, has just noticed the Knorr Global Flavors Passport Stall for the first time — he's mid-step, stopped, staring up at the departures board with genuine wide-eyed surprise, one hand pointing up at it, the other grabbing his friend's arm. The stall visible behind him, "SEOUL — NOW BOARDING" legible on the board. Small floating white label bottom-left: "01 PLACE." CENTER THIRD — slightly softer focus: the same student now seated at a table at the stall, black blindfold on, both hands around a steaming Knorr black noodle cup, mouth open mid-laugh — a Pakistani girl beside him in an oversized jacket has her phone up in portrait mode, TikTok recording interface visible on the screen, red record dot active. Small floating label: "02 PARTICIPATION." RIGHT THIRD — soft focus background, but his friend's phone screen pulled into sharpness via a slight foreground push: Instagram Reels post already live — the video of him blindfolded playing in the feed, view counter reading "24.3K", comments section showing "bro thought it was Italian 💀", "Knorr really said world tour 🌍", share button glowing. Small floating label: "03 PROOF." Floating in the dark sky above in large white condensed bold: "ONE STUDENT. ONE BOWL. ONE MILLION VIEWS." Subtext: "Place. Participation. Proof." Cinematic grain. Deep vignette on edges.`,

  `Breathtaking top-down isometric 3D render, Unreal Engine 5 Lumen lighting, 4K photorealistic textures. A dense South Asian urban grid modeled after Lahore's inner city — thousands of individually rendered kirana stores, general trade outlets, pharmacies, and street stalls. Each building has corrugated iron awnings, hand-painted Urdu signage, goods stacked in doorways: flour sacks, biscuit racks, cold drink crates. Overhead electrical cables crisscross like spider webs between rooftops. Street vendors with pushcarts dot the lanes. But 35% of all stores across the map are rendered in cold desaturated grey — hollow, ghosted, drained of color and life — as if faded from existence, with a faint blue mist hovering over them. The remaining 65% glow in warm amber-gold light, bustling with simulated commerce. Red dotted delivery route lines zig-zag between only the glowing stores — pointedly curving around and ignoring every grey outlet. A lone 3D-rendered salesman figure — detailed: collared shirt, leather satchel, clipboard, worn shoes — stands at a glowing route junction, back slightly turned toward the grey zones, completely unaware. Above the scene, a massive glowing red statistic floats in bold 3D numerals: "30–40% OF YOUR MARKET HAS NEVER SEEN YOUR SALESMAN." Beneath it, smaller text: "Unmapped. Under-served. Invisible." Dramatic overhead spotlight lighting on the active zones, cool blue ambient fill on the grey ones. Cinematic depth-of-field blur softening the far edges of the map.`,

  `Stark, deeply moody cinematic interior photograph, shot on Leica SL2 with 50mm Noctilux f/0.95, available light only. A cavernous industrial logistics planning room — raw concrete walls, exposed steel I-beam ceiling, cold blue-white fluorescent tubes casting hard shadows on the floor. At the center of the frame: a massive pinboard wall, 12 feet wide, entirely covered in overlapping distribution route maps — Pakistan territory maps in various generations, the oldest ones yellowed and curling at the edges, pinned over and over by different colored map pins. Red marker lines trace delivery routes across the maps — some routes circled three, four, five times in frustrated loops, annotations scrawled in urgent handwriting: "still same as 2015", "why no growth?", "dead zone?" A tangle of red string connects pins across different maps, some threads loose and hanging. Scattered across the concrete floor in front of the pinboard: stacks of aged delivery manifests, curling territory printouts, a 2015 desk calendar lying open and abandoned, a coffee mug long gone cold. A single figure in a crisp dark business suit stands with his back to the camera, arms loosely crossed, facing the pinboard — head slightly tilted, the posture of someone processing an uncomfortable truth. A single industrial pendant lamp directly above him casts a dramatic downward spotlight, leaving everything beyond six feet in deep shadow. On the concrete wall above the pinboard, in large white block stencil letters: "2015 → 2024. SAME ROUTES." Cinematic color grade: desaturated cool greys and blues, single warm amber accent on the lamp cone. Heavy film grain overlay.`,

  `Ultra-realistic business case study infographic, clean white background with subtle blue-grey tonal depth. The dominant element is a large, professionally rendered line graph occupying the CENTER 70% of the slide — styled like a McKinsey or BCG case exhibit. X-axis: years from 2000 to 2007. Y-axis: Volume Index (100 = baseline). The line starts at 100 in 2000, grows modestly to 115 by 2002, then visibly flattens — a near-horizontal plateau from 2002 to 2003, the line nearly dead flat. Then at 2003, a sharp annotation marker drops from the top: a bold vertical dotted line labeled in a clean callout box: "GO-TO-MARKET TRANSFORMATION LAUNCHED" with a small sub-label: "Tier 2 & Tier 3 mapping. Distributor networks rebuilt." From 2003, the line breaks sharply upward at a steep angle — climbing aggressively through 2004, 2005, 2006, ending at 400 on the Y-axis by 2007. The area under the post-2003 curve is filled with a soft blue gradient. At the 2007 endpoint, a large bold callout bubble: "4X VOLUME" in massive dark type. The plateau section of the line is colored red and annotated: "Tier 1 saturation". The growth section is colored electric blue. Below the graph, a thin dark rule, then a three-column insight strip: "DECISION:" "Go deeper, not wider" | "METHOD:" "Tier 2 & Tier 3 market mapping" | "RESULT:" "4x volume in five years". At the top of the slide in bold dark condensed: "THEY DIDN'T CHANGE THE PRODUCT. THEY CHANGED THE MAP." Looks like a real HBR case study exhibit — data-precise, visually undeniable.`,
];

const numberedExamples = MINIMALISTIC_EXAMPLE_PROMPTS
  .map((p, i) => `[${i + 1}]\n${p}`)
  .join('\n\n');

// Drop-in style block shared by every minimalistic system prompt. It teaches the
// style purely by example, with guardrails so the model adapts the *style* to
// the user's brief instead of copying the examples' subjects.
export const MINIMALISTIC_STYLE_REFERENCE = `══════════════════════════════════════════
MINIMALISTIC STYLE — LEARN FROM THESE REFERENCE PROMPTS
══════════════════════════════════════════

The image prompt you write must match the STYLE of the reference prompts below. Study their voice, structure, sentence rhythm, and level of detail. Like them, your prompt should: commit to exactly ONE render medium (a cinematic photograph with a named camera + lens / an editorial infographic exhibit / a hyper-dramatic 3D product render / a top-down isometric 3D render); build the frame around ONE strong central idea — a single hero moment or one dominant metaphor object, never a busy collage or a grid of pills; use a restrained, near-monochrome palette with at most one accent colour; carry a large condensed or stencil headline plus a fine subtext line that pairs a hard stat with its consequence; quote any on-image text verbatim; and finish with a stated cinematic colour grade, heavy film grain, and a deep vignette.

THESE ARE STYLE REFERENCES ONLY. They describe other brands and topics (Knorr, Unilever, a SaaS app, Pakistani campaigns, the "Place / Participation / Proof" framework). NEVER copy their subjects, brands, companies, products, statistics, place names, headlines, or copy. Invent fresh subject matter that fits THE USER'S brief and the specific slide, rendered in this same style.

Do NOT end your prompt with "Aspect ratio 16:9" and do NOT mention aspect ratio anywhere — it is handled separately as an API parameter.
Never fall back to generic stock clichés: no "business people in a meeting", "person using laptop", "team collaborating in office", "handshake", "growth chart", "abstract gradient background", "glowing orbs".

REFERENCE PROMPTS
─────────────────
${numberedExamples}

══════════════════════════════════════════
END REFERENCE PROMPTS — now write in this exact style for the user's slide.
══════════════════════════════════════════`;
