/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        ios: {
          blue: '#007AFF',
          green: '#34C759',
          indigo: '#5856D6',
          orange: '#FF9500',
          pink: '#FF2D55',
          purple: '#AF52DE',
          red: '#FF3B30',
          teal: '#5AC8FA',
          yellow: '#FFCC00',
          gray1: '#8E8E93',
          gray2: '#AEAEB2',
          gray3: '#C7C7CC',
          gray4: '#D1D1D6',
          gray5: '#E5E5EA',
          gray6: '#F2F2F7',
        },
        hb: {
          // Brand core
          primary:        '#8B5CF6',
          'primary-dark': '#7C3AED',
          'primary-light':'#C4B5FD',
          secondary:      '#00F0FF',
          'secondary-dark':'#00C4D4',
          tertiary:       '#B06B00',
          'tertiary-light':'#F59E0B',
          // Dark surfaces
          dark:           '#0A0A0B',
          'dark-mid':     '#111113',
          surface:        '#18181B',
          'surface-2':    '#1F1F23',
          border:         '#2E2E35',
          // Light surfaces (dashboard)
          app:            '#F5F3FF',
          'app-card':     '#FFFFFF',
          'app-border':   '#EDE9FE',
          text:           '#18132E',
          muted:          '#6B6285',
        },
      },
      fontFamily: {
        sans: ['Geist', '-apple-system', 'BlinkMacSystemFont', '"Helvetica Neue"', 'Arial', 'sans-serif'],
        serif: ['Newsreader', 'Georgia', 'serif'],
        display: ['Newsreader', 'Georgia', 'serif'],
      },
      borderRadius: {
        '2xl': '16px',
        '3xl': '22px',
        '4xl': '32px',
      },
      boxShadow: {
        ios:       '0 2px 12px rgba(0,0,0,0.08)',
        'ios-md':  '0 4px 20px rgba(0,0,0,0.10)',
        'ios-lg':  '0 8px 32px rgba(0,0,0,0.12)',
        'ios-xl':  '0 20px 60px rgba(0,0,0,0.18)',
        'hb-glow':      '0 0 40px rgba(139,92,246,0.35)',
        'hb-glow-cyan': '0 0 40px rgba(0,240,255,0.30)',
        'hb-card':      '0 4px 32px rgba(10,10,11,0.25)',
      },
      keyframes: {
        fadeIn:    { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp:   { '0%': { opacity: '0', transform: 'translateY(24px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideDown: { '0%': { opacity: '0', transform: 'translateY(-12px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        scaleIn:   { '0%': { opacity: '0', transform: 'scale(0.92)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
        shimmer:   { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        float:     { '0%, 100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-8px)' } },
      },
      animation: {
        fadeIn:   'fadeIn 0.3s ease-out',
        slideUp:  'slideUp 0.4s cubic-bezier(0.16,1,0.3,1)',
        slideDown:'slideDown 0.3s cubic-bezier(0.16,1,0.3,1)',
        scaleIn:  'scaleIn 0.25s cubic-bezier(0.16,1,0.3,1)',
        shimmer:  'shimmer 2s linear infinite',
        float:    'float 3s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
